[package]
name = "blink"
version = "0.0.0"
edition = "2024"

[dependencies]
goblin = { version = "0.10.3" }
anyhow = { version = "1" }
byteorder = "1.5.0"
tempfile = "3.23.0"
base64ct = "1.8.0"
sha256 = "1.6.0"
rand = "0.9.2"
